package mockup.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Pattern_Constraints extends BaseConstraintsDescriptor {
  public Pattern_Constraints() {
    super("mockup.structure.Pattern");
  }
}
