package mockup.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class Applat_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_evaluate_6035835504269173056(SNode thisNode, final List<SNode> binding) {
    SNode result = SConceptOperations.createNewNode("mockup.structure.Applat", null);
    ListSequence.fromList(SLinkOperations.getTargets(result, "content", true)).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "content", true)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), it, "virtual_evaluate_6035835504269173056", new Object[]{binding});
      }
    }));
    return result;
  }
}
