package mockup.behavior;

/*Generated by MPS */


public class Applat_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Applat_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Applat";
  }
}
