package mockup.behavior;

/*Generated by MPS */


public class BarreEtapes_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public BarreEtapes_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.BarreEtapes";
  }
}
