package mockup.behavior;

/*Generated by MPS */


public class Button_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Button_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Button";
  }
}
