package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

public abstract class Component_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Component_BehaviorDescriptor() {
  }

  public SNode virtual_evaluate_6035835504269173056(SNode thisNode, List<SNode> binding) {
    return Component_Behavior.virtual_evaluate_6035835504269173056(thisNode, binding);
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Component";
  }
}
