package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Etape_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Etape_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Etape";
  }
}
