package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.core.xml.behavior.XmlContent_BehaviorDescriptor;

public class ExpressionWrapper_BehaviorDescriptor extends XmlContent_BehaviorDescriptor {
  public ExpressionWrapper_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.ExpressionWrapper";
  }
}
