package mockup.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class Form3Element_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_evaluate_6035835504269173056(SNode thisNode, final List<SNode> binding) {
    SNode result = SConceptOperations.createNewNode("mockup.structure.Form3Element", null);
    SLinkOperations.setTarget(result, "libelle", BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "libelle", true), "virtual_evaluate_6035835504269252966", new Object[]{binding}), true);
    ListSequence.fromList(SLinkOperations.getTargets(result, "values", true)).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "values", true)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), it, "virtual_evaluate_6035835504269173056", new Object[]{binding});
      }
    }));
    return result;
  }
}
