package mockup.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

public class Form3Element_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Form3Element_BehaviorDescriptor() {
  }

  public SNode virtual_evaluate_6035835504269173056(SNode thisNode, List<SNode> binding) {
    return Form3Element_Behavior.virtual_evaluate_6035835504269173056(thisNode, binding);
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Form3Element";
  }
}
