package mockup.behavior;

/*Generated by MPS */


public class Form3Element_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Form3Element_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Form3Element";
  }
}
