package mockup.behavior;

/*Generated by MPS */


public class Heading_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Heading_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Heading";
  }
}
