package mockup.behavior;

/*Generated by MPS */


public class InputText_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public InputText_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.InputText";
  }
}
