package mockup.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class Label_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_evaluate_6035835504269173056(SNode thisNode, List<SNode> binding) {
    SNode result = SConceptOperations.createNewNode("mockup.structure.Label", null);
    SLinkOperations.setTarget(result, "text", BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "text", true), "virtual_evaluate_6035835504269252966", new Object[]{binding}), true);
    return result;
  }
}
