package mockup.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

public class Label_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Label_BehaviorDescriptor() {
  }

  public SNode virtual_evaluate_6035835504269173056(SNode thisNode, List<SNode> binding) {
    return Label_Behavior.virtual_evaluate_6035835504269173056(thisNode, binding);
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Label";
  }
}
