package mockup.behavior;

/*Generated by MPS */


public class Label_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public Label_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Label";
  }
}
