package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Mockup_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Mockup_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Mockup";
  }
}
