package mockup.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

public class ParameterReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ParameterReference_BehaviorDescriptor() {
  }

  public SNode virtual_evaluate_6035835504269252966(SNode thisNode, List<SNode> binding) {
    return ParameterReference_Behavior.virtual_evaluate_6035835504269252966(thisNode, binding);
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.ParameterReference";
  }
}
