package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ParameterValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ParameterValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.ParameterValue";
  }
}
