package mockup.behavior;

/*Generated by MPS */


public class ParameterReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ParameterReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.ParameterReference";
  }
}
