package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PatternReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PatternReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.PatternReference";
  }
}
