package mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Step_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Step_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.Step";
  }
}
