package mockup.behavior;

/*Generated by MPS */


public class StringLiteral_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public StringLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mockup.structure.StringLiteral";
  }
}
